version: "3.9"

services:
  cnterra-loader:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnterra-loader:1.0
    container_name: cnterra-loader
    environment:
      NODE_ID: 1
      LOADER_PORT: 8080
      SERIAL_PORT: /dev/ttyUSB0
      RABBITMQ_ADDRESS: localhost
    restart: always
    entrypoint: /opt/cnterra-loader/start.sh
    devices:
      - /dev/ttyUSB0
    ports:
      - 8080:8080
    volumes:
      - /opt/cnterra-loader/tmp:/opt/cnterra-loader/tmp
    networks:
      - cnterra-net

networks:
  cnterra-net:
    name: cnterra-net
