version: "3.9"

services:
  cnterra-rabbitmq:
    image: rabbitmq:3.9
    container_name: cnterra-rabbitmq
    ports:
      - 5672:5672
    networks:
      - cnterra-net

  cnterra-loader:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnterra-loader:1.0
    container_name: cnterra-loader
    environment:
      CNTERRA_SERIAL: /dev/ttyUSB0
    restart: always
    entrypoint: /opt/cnterra-loader/start.sh
    devices:
      - /dev/ttyUSB0
    volumes:
      - /opt/cnterra-loader/tmp:/opt/cnterra-loader/tmp
    networks:
      - cnterra-net
    depends_on:
      - cnterra-rabbitmq

networks:
  cnterra-net:
    name: cnterra-net
